### ISSUE TITLE
Support for error handlers registered using decorators

### ISSUE THREAD

**Issue by RobertoPrevato** [Neoteroi/BlackSheep#111]
It would be interesting to support the same way to register error handlers using decorators, like in Flask:

![image](https://user-images.githubusercontent.com/2576032/116009070-c84ed400-a617-11eb-80f5-ed50009f1927.png)

https://twitter.com/testdrivenio/status/1384398245648994307

**Comment by myusko** [comment]
@RobertoPrevato Hey,

Sounds interesting, if no one doesn't work on this, I'll happy to take it, once I've got a free time.

**Comment by RobertoPrevato** [comment]
Hi @myusko, yes please, I would appreciate that very much. 
The application class has a property, `exceptions_handlers` used to define exception handlers by status or by exception class.

Inside the file `test_application.py` you can find some examples of exception handlers defined by status code (`test_application_http_exception_handlers`) and  by exception class (e.g. `test_application_user_defined_exception_handlers`)

**Comment by myusko** [comment]
@RobertoPrevato Thank you for the information!
