### ISSUE TITLE
Add TestClient for server testing

### ISSUE THREAD

**Issue by myusko** [Neoteroi/BlackSheep#117]
Hey,

I believe would be great to add `TestClient` in order to achieve neat testability of the server, and provide a greater experience for the programmers.

My thoughts, it should be looks like the example below.

```python
# applicatio.py
from blacksheep import Application
from blacksheep.server.responses import json

app = Application()

@app.route("/")
async def home(request):
     return json({"foo": "bar"})


# test_app.py
from application import app

def test_home_route():
     app = TestClient(app)
     response = app.simulate_get("/")

     assert response.json()["foo"] == "bar"
```

**Comment by RobertoPrevato** [comment]
Hi,
Very good idea, again. 😄 I would recommend naming the methods with `get`, `post`, `put`, etc. (without "simulate_").

The test client should also support the built-in strategy for authentication, maybe accepting a `user` argument for each method, or a context manager, like

```python
client = TestClient(app)

with client.user_context(User(...)):
    response = await client.get("/example")
    ...
```

**Comment by RobertoPrevato** [comment]
@myusko as a side note, since version `1.0.2`, you can write your example above this way:

```python
from blacksheep import Application

app = Application()

@app.route("/")
async def home():
     return {"foo": "bar"}
```

Or, even better because you gain automatic OpenAPI Documentation for responses:

```python
from dataclasses import dataclass

from blacksheep import Application

app = Application()


@dataclass
class Example:
    foo: str


@app.route("/")
async def home() -> Example:
     return Example(foo="bar")
```

The same works with `Pydantic` models.

**Comment by myusko** [comment]
@RobertoPrevato Yeah, also agree with the built-in strategy for authentication, also I'd suggest prioritizing this issue, since, have a possibility easy to test an API/service, etc, which is very important nowadays.

Also, since you're creator and maintainer of the framework, it will be really great to hear your opinion, how the TestClient API should look like, what we should avoid, etc.

**Comment by RobertoPrevato** [comment]
I need to think a bit about this. These days I am working on an advanced demo project / project template for Azure web apps, as I [described in Twitter](https://twitter.com/RobertoPrevato/status/1388033944130662401).

I agree this is an important feature. I will share my thoughts after publishing and documenting the project template, and come up with some proposal.

**Comment by myusko** [comment]
Nice to hear it, because I've been thinking about it yesterday and today, and can't see any suitable implementation, which will satisfy all needs.

Since, in the `Application.__call__()` we're passing parameters which `asgi` expecting, and we don't operate with the `Response` class directly. And probably that's the main blocker for me, right now.

I've tried really simple implementations
```
class TestClient:
    def __init__(self, app):
        self.app = app
        
    async def get(self):
        await self.app(get_example_scope("GET", "/"), MockReceie(), MockSend())
```
This scenario will work, but unfortunately, we don' have access to the `Response` class, and as a result, we can't return anything.

Second example
```
class TestClient:
    def __init__(self, app):
        self.app = app

    async def get(self):
        request = Request.incoming(...)
        response = await self.app.handle(request)
        return response
```
It will work only for all successful HTTP status codes, but it won't work in case if 500 returns, since, handle method doesn't handle exceptions directly, probably I may be wrong here.

**Comment by RobertoPrevato** [comment]
@myusko I'll need to wrap my head around this subject a bit. As I said I am now focused on sharing a project template for projects to be published in Azure, with some advanced topics. It won't take many hours to share my project template, since I've already created a private project that uses the same things.

About the `TestClient`, I would prefer to make it abstracted from `ASGI`, because I don't exclude to reimplement a Cython HTTP Server at some point in time (please take a look at [this](https://github.com/Neoteroi/BlackSheep/releases/tag/before-asgi)), to support both `ASGI` and a server that might benefit from `Cython`.

Note:
* when I started `blacksheep` I had close to no experience with `Cython`, I think if I knew how to use `httptools` directly using git sub-modules and importing its header files, `BlackSheep`'s performance could be superior compared to how it is today

Therefore, I would rather make the `TestClient` interact with the `Application.handle` method.

**Comment by myusko** [comment]
@RobertoPrevato Hey, please don't consider it as "pushing" you to provide immediately your ideas, I just played with TestClient, and looking how we can implement it, and then decided to share my ideas:)

**Comment by RobertoPrevato** [comment]
No worries, I don't feel like you are pushing :) on the contrary, I am happy that you are helping with this project and I appreciate it very much. 🌞 
I'll write more later.

**Comment by myusko** [comment]
Nice to hear it, I think that I have really small progress regarding TestClient, and I believe it will be a small start for future implementation.

And a good place to discuss further steps. I'll try to send a PR in few days.

Thank you, @RobertoPrevato

**Comment by myusko** [comment]
Small update from my side, I didn't start yet a draft implementation, due to fact that I don't have enough free time=(

**Comment by RobertoPrevato** [comment]
No pressure. I also don't work full time on this project. I have a full time job from Monday to Friday. 😄 on my side, I actually switched temporarily to issue #124 because it's missing and it can be added in relatively short time.

**Comment by myusko** [comment]
Update: Didn't touch the TestClient yet.
