### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by myusko** [Neoteroi/BlackSheep#120]
The documentation said that we can set cookies in this way

```
from blacksheep.server import Application
from blacksheep.server.responses import json
from blacksheep.cookies import Cookie

app = Application()
get = app.router.get


@get("/")
def home():
    response = json({"message": "Hello, World!"})

    response.set_cookie(Cookie(b"foo", b"value"))

    return response
```

I expect that cookies will be set.

**Actual result**

We're getting an error
```
Traceback (most recent call last):
  File "blacksheep/baseapp.pyx", line 78, in blacksheep.baseapp.BaseApplication.handle
    response = await route.handler(request)
  File "./blacksheep/server/normalization.py", line 501, in handler
    result = await method(request)
  File "./blacksheep/server/normalization.py", line 437, in handler
    return method()
  File "./tes.py", line 17, in home
    response.set_cookie(Cookie(b"foo", b"value"))
TypeError: Argument 'name' has incorrect type (expected str, got bytes)
```

**Comment by RobertoPrevato** [comment]
I am fixing this, by the way the documentation around cookies is poor. I will take the occasion to improve it.

I just noticed that even the stub file is out of date, it doesn't document properly the `CookieSameSiteMode` enum.

**Comment by RobertoPrevato** [comment]
That error in the documentation has been fixed:
https://www.neoteroi.dev/blacksheep/responses/#setting-cookies

Contextually, two mistakes in Python stub files are going to be fixed in the framework's source code.

**Comment by myusko** [comment]
Nice-nice!
