### ISSUE TITLE
Recent failing

### ISSUE THREAD

**Issue by waghanza** [Neoteroi/BlackSheep#131]
Hi @RobertoPrevato 

When staring https://github.com/the-benchmarker/web-frameworks/blob/master/python/blacksheep/server.py, I have (recently) the following

```python
/usr/src/app/server.py:28: RuntimeWarning: coroutine 'Application.start' was never awaited
  app.start()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

Related to https://github.com/the-benchmarker/web-frameworks/issues/4282

Regards,

**Comment by RobertoPrevato** [comment]
Hi @waghanza 
Sorry for not being so active in `the-benchmarker`. I can fix this, the `app.start()` method should not be called this way anymore, since the framework is now using ASGI.

I'll check this as soon as I can (maybe later today).

**Comment by waghanza** [comment]
> Sorry for not being so active in the-benchmarker

np, we have all activities alongside OSS

> I'll check this as soon as I can (maybe later today).

ok, thanks. I'll wait your fix to publish new result on https://web-frameworks-benchmark.netlify.app, our new UI

**Comment by RobertoPrevato** [comment]
Hi @waghanza,
I created a PR, I tested locally and it works after my fix. The `app.start()` wasn't needed anymore (Uvicorn emits start events). 😄  https://github.com/the-benchmarker/web-frameworks/pull/4304

**Comment by waghanza** [comment]
waiting for https://github.com/encode/uvicorn/pull/1024 (actual version of `BlackSheep` is incompatible with **Cython** based tools on `uvicorn`, mainly `uvloop`)

**Comment by RobertoPrevato** [comment]
OK - testing with Alpine I think there are two options:

1. installing `uvicorn` without `[standard]` clause: uvicorn should use anyway httptools because it will be available at runtime (it's a dependency for `blacksheep` http client implementation)
2. lock `blacksheep` to `1.0.3` until `uvicorn[standard]` will reference the older version of httptools

**Comment by waghanza** [comment]
CI is ok for me
https://the-benchmarker.semaphoreci.com/jobs/1ab5ec4f-af57-4c05-8032-13f90bc8476f

I prefer the second solution, since it use the same tooling as other  `asgi` framework, the first solution will mislead results, imhp
