### ISSUE TITLE
Add support for mounting ASGI apps

### ISSUE THREAD

**Issue by RobertoPrevato** [Neoteroi/BlackSheep#161]
As recommended in https://github.com/Neoteroi/BlackSheep/discussions/160

**Comment by RobertoPrevato** [comment]
**Notes:** since BlackSheep converts ASGI dictionaries into its specialized classes, it won't be possible to implement mounting by simply modifying the `Router` class, as happens in `Starlette`. An Application supporting `mount` needs to have its `__call__` modified.

One of the reasons why BlackSheep has a decent performance, it's because it's designed to avoid "fees" when features are not used. Therefore, I recommend using a mixin object that adds the optional feature, rather than modifying the current `Application` class (i.e. users who don't want to use this specific feature shouldn't pay a performance fee at each web request, while it's reasonable having to pay a fee when _opting-in_ for a feature - the same principal was applied to middlewares, automatic binding of parameters, and in general all non-essential features in the framework).

**Example:**

```python

class Mount:
    """This should be compatible with the mount for Starlette: app, path"""
    def __init__(self, app, path):
        self.app = app
        self.path = path

    async def handle(self, scope, receive, send):
        return await self.app(scope, receive, send)


class MountMixin:
    # TODO: initialize _mounted_apps overriding __init__ or in a property like below 
    _mounted_apps: Optional[List[Mount]] = None

    @property
    def mounted_apps(self) -> List[Mount]:
        if self._mounted_apps is None:
            self._mounted_apps = []
        return self._mounted_apps

    def mount(self, app, path) -> None:
        self.mounted_apps.append(Mount(app, path))

    async def __call__(self, scope, receive, send):
        if scope["type"] == "lifespan":
            return await self._handle_lifespan(receive, send)

        # before creating an instance of Request, check if this request shouldn't be handled by
        # one of the mounted apps (apps are mounted under a certain path prefix, therefore check if
        # any of the mounted apps doesn't handle the current ASGI scope's path)
        for mount in self.mounted_apps:
            if mount.is_match(scope["raw_path"]):
                  return await mount.handle(scope, receive, send)

        return await super().__call__(scope, receive, send)
```


Then, to opt in for this feature:

```python
class MountApp(Application, MountMixin):
     ...
```

**Comment by myusko** [comment]
Yes, to be honest, I had the same idea, since adding this functionality to the `Application` class will be expensive from the performance perspective.

I going to create a PR in 2-3 days.

**Comment by RobertoPrevato** [comment]
We might include an ` ASGIApplication` which includes by default extra features (asgi-specific) like mounting. In such case without the mixin (mixin has the downside that if one wishes to use "super().__call__" the order of classes matters. 😸

**Comment by myusko** [comment]
I have one more thing to say,

Probably we can add the flag`use_mount=True` to the `Application` constructor, does this make sense?

e.g

```python
class Application(BaseApplication):
    def __init__(use_mount=False):
          if use_mount:
                self._mount = Mount()
            .......

     def mount():
         self._mount.add(...)
```

**Comment by RobertoPrevato** [comment]
Since we don't want to modify the base `__call__` method, I would avoid modifying the constructor of the base `Application` class with properties that are not used by `Application` itself. I would prefer a sub-constructor like:

```python
class ASGIApplication(Application):
    def __init__(self, *, router: Optional[Router], services: Optional[Container], debug: bool, show_error_details: Optional[bool]):
        super().__init__(router=router, services=services, debug=debug, show_error_details=show_error_details)
        self._mount = ...
```

or:

```python
class ASGIApplication(Application):
    def __init__(self, *, mount: ..., **kwargs):
        super().__init__(**kwargs)
        self._mount = mount
```

I know there is a bit of code repetition for the `4` constructor arguments like in the first case, but I personally prefer it over the `**kwargs` option because the code is more type-friendly when using a text editor that helps with the function's arguments.
