### ISSUE TITLE
Add Extensions section the README file

### ISSUE THREAD

**Issue by myusko** [Neoteroi/BlackSheep#164]
## 🚀 Feature Request
Add Extension onto the README file

###  Description
It allows to users find quickly links for BlackSheep's extensions.

**Comment by RobertoPrevato** [comment]
Good idea. I only recommend to add it once we have three or four extensions at least.

Right now we have one for `SQLAlchemy`. We could prepare one for [`Piccolo-ORM`](https://piccolo-orm.readthedocs.io/en/latest/piccolo/engines/postgres_engine.html) very quickly, as recommended earlier today by the anonymous GitHub user.

On top of the TODO list in my mind there is preparing two packages for:
* OpenCensus - using code I already written for the demo project, it only needs packaging and preparing a project
* OpenCensus + Azure Application Insights - same as above
* [OpenTelemetry](https://lightstep.com/blog/brief-history-of-opentelemetry/) (API merged from OpenCensus and OpenTracing)
* raw `asyncpg` connection pooling / db connections

**Maybe** we could put the `pydantic` handling logic as part of the OAD generation into a dedicated package, this is something I'm considering but not sure abou
