### ISSUE TITLE
Add support for pydantic custom types (e.g. UrlStr) in OpenAPI Doc generation

### ISSUE THREAD

**Issue by RobertoPrevato** [Neoteroi/BlackSheep#167]
**🚀 Feature Request**
Like in title. See also the custom types used by Piccolo ORM (https://github.com/Neoteroi/BlackSheep/issues/163)

**Comment by RobertoPrevato** [comment]
Fixed in `v1.0.7` - it now needs documentation.

**Comment by adriangb** [comment]
@RobertoPrevato I was looking for issues to pick up in BlackSheep, this seems like a reasonably easy one to start with. However, I couldn't find where the docs are, they don't seem to be in this repo. Would you mind pointing me to where the docs are stored?

As for the documentation itself, I imagine this should be pretty simple, basically a blurb saying that the feature is supported and a simpler version of the [existing test](https://github.com/Neoteroi/BlackSheep/blob/88679b653334072127830f442300ed5823764fcf/tests/test_openapi_v3.py#L1712-L1792). Does that sound good?

Also, I've set up several projects w/ CI/CD for Mkdocs + GitHub Pages, so I'm happy to help with that as well e.g. to move #146 forward.

**Comment by RobertoPrevato** [comment]
Sure @adriangb - and thank you for helping.
The documentation is currently stored in Azure DevOps - I am planning since a long time to transfer it to GitHub, but I didn't have the time to do it, yet.

It is currently here -> https://dev.azure.com/robertoprevato/BlackSheep/_git/Docs
It's also using Git.

> As for the documentation itself, I imagine this should be pretty simple, basically a blurb saying that the feature is supported and a simpler version of the existing test. Does that sound good?

Yes, sounds very good. 

> Also, I've set up several projects w/ CI/CD for Mkdocs + GitHub Pages

About this, I would only like to move the documentation to GitHub - I like it to be in a separate repository, and move to GitHub Workflows but always publishing HTML to the Azure Storage service I am using to host the documentation (served using Azure Front Door).

**Comment by adriangb** [comment]
> It is currently here -> https://dev.azure.com/robertoprevato/BlackSheep/_git/Docs
> It's also using Git.

👍 will take a look

> About this, I would only like to move the documentation to GitHub - I like it to be in a separate repository - and move to GitHub Workflows but always publishing HTML to the Azure Storage service I am using to host the documentation (served using Azure Front Door).

Is there any particular reason for this? Most OS project that I know of use either GitHub pages or RTD.

**Comment by adriangb** [comment]
Fair enough! I was just curious 😄
