### ISSUE TITLE
Add useful packages to documentation

### ISSUE THREAD

**Issue by Cdayz** [Neoteroi/BlackSheep#172]
Hi, I made a package to integrate with prometheus, it would be cool if ecosystem packages for blacksheep were mentioned in the documentation.

Package: https://github.com/Cdayz/blacksheep-prometheus
PyPI: https://pypi.org/project/blacksheep-prometheus/

**Comment by RobertoPrevato** [comment]
Hi @Cdayz
Thank you! I am working on the documentation these days, and I was going to add a section for external packages. I will surely add yours to the list.

**Comment by Cdayz** [comment]
Hi, I'm on a roll today, I made another useful package for blacksheep - blacksheep-context.
Package: https://github.com/Cdayz/blacksheep-context
PyPI: https://pypi.org/project/blacksheep-context/

**Comment by myusko** [comment]
Hi @Cdayz These packages look awesome! Thank you for your hard work.
