### ISSUE TITLE
Deploy to Deta.sh error: Exception in ASGI application

### ISSUE THREAD

**Issue by Ppang0405** [Neoteroi/BlackSheep#183]
**Describe the bug**
I just try deploying the example code to Deta Micros and it got the error.

main.py

```
from datetime import datetime
from blacksheep.server import Application
from blacksheep.server.responses import text


app = Application()

@app.route("/")
async def home(request):
    return text(f"Hello, World! {datetime.utcnow().isoformat()}")`
```
    
**Response**
"Internal Server Error"
![Screen Shot 2021-07-10 at 22 13 04](https://user-images.githubusercontent.com/33455900/125167691-034eb580-e1cc-11eb-932a-6da27a5f7cd8.png)

**Log**
```
[ERROR]	2021-07-10T14:54:24.243Z	18cdc174-eb67-4040-b58b-9aa662fb9b77	Exception in ASGI application
Traceback (most recent call last):
  File "/opt/python/detalib/adapters/asgi/protocols/http.py", line 47, in run
    await app(self.scope, self.receive, self.send)
  File "/opt/python/blacksheep/server/application.py", line 606, in __call__
    response = await self.handle(request)
  File "blacksheep/baseapp.pyx", line 72, in handle
  File "blacksheep/baseapp.pyx", line 66, in blacksheep.baseapp.BaseApplication.get_route_match
  File "/opt/python/blacksheep/server/routing.py", line 432, in get_match
    match = route.match(ensure_bytes(value))
  File "/opt/python/blacksheep/utils/__init__.py", line 10, in ensure_bytes
    raise ValueError("Expected bytes or str")
ValueError: Expected bytes or str
No errors
```

Please check it https://www.deta.sh/, the other ASGI/WSGI framework: Flask, FastAPI worked.

**Comment by RobertoPrevato** [comment]
Hi @Ppang0405, thanks for posting this issue.
I took a look at Deta, and I cannot find easily the source code of "/../detalib/adapters/asgi/protocols/http.py".

I also don't have time these days to read the terms and condition to sign-up for Deta to test it.

Could you please help me, telling what is the type of `value` there? The path should be `str` or `bytes`.
