### ISSUE TITLE
Ability to set a single handler for all exceptions that inherit from a base exception

### ISSUE THREAD

**Issue by YassineElbouchaibi** [Neoteroi/BlackSheep#188]
**🚀 Feature Request**

Ability to set a single handler for all exceptions that inherit from a base exception. However, the exception handler mapper would need to always resolve to the youngest descendant for an exception.

This is useful when using a third party library which has a lot of specific exceptions that you want to handle in the same way.

If this is deemed useful for everyone and implemented before : #186, then I believe #186 could be closed as one could set a handler for Exception which would always be called last if there is no handler for the rest of the exception's hierarchy.

**Comment by RobertoPrevato** [comment]
This is another very good recommendation, we will look into this and see if it creates any side effect - but I don't think so. I think #186 would make sense in any case. :)

**Comment by myusko** [comment]
Good suggestion, I love it!

**Comment by mohd-akram** [comment]
Why was this closed? I'm running into this issue right now:

```python
from blacksheep.server import Application

app = Application()

@app.router.get('/type-error')
async def type_error():
    raise TypeError()

@app.router.get('/exception')
async def exception():
    raise Exception()

@app.exception_handler(Exception)
async def handler(self, request, exception):
    print('caught', exception.__class__.__name__)
```

`curl localhost:8000/exception` (works correctly):

```python
caught Exception
INFO:     127.0.0.1:57774 - "GET /exception HTTP/1.1" 204 No Content
```

`curl localhost:8000/type-error` (weird):

```python
Unhandled exception - "GET /type-error"
Traceback (most recent call last):
  File "blacksheep/baseapp.pyx", line 84, in blacksheep.baseapp.BaseApplication.handle
  File "/Users/user/Library/Python/3.11/lib/python/site-packages/blacksheep/server/normalization.py", line 543, in handler
    return ensure_response(await method(request))
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Python/3.11/lib/python/site-packages/blacksheep/server/normalization.py", line 513, in handler
    return await method()
           ^^^^^^^^^^^^^^
  File "/tmp/main.py", line 7, in type_error
    raise TypeError()
TypeError
caught TypeError
INFO:     127.0.0.1:57772 - "GET /type-error HTTP/1.1" 204 No Content
```
