### ISSUE TITLE
Dependency mismatch between blacksheep 1.2.0 and uvicorn[standard] 0.15.0

### ISSUE THREAD

**Issue by waghanza** [Neoteroi/BlackSheep#199]
Hi @RobertoPrevato ,

The last release fails on https://github.com/the-benchmarker/web-frameworks/pull/4774.

The backtrace is 
```
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 371, in run_asgi
    asgi = app(self.scope)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 33, in __call__
    return MessageLoggerResponder(scope, self.app, self.logger, self.task_counter)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 51, in __init__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 47, in __init__
    self.inner = app(scope)
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'
```

**Comment by RobertoPrevato** [comment]
Hi @waghanza,
Thank You for opening this issue. I'll check it as soon as possible.

**Comment by RobertoPrevato** [comment]
Hi @waghanza 
I cannot reproduce the problem, I recreated the same scenario as in your PR https://github.com/the-benchmarker/web-frameworks/pull/4774

using the last version of BlackSheep, last versions of uvicorn and gunicorn, and I don't get the error both when running uvicorn directly without gunicorn, and with gunicorn.

I see that the wrong version of uvicorn is getting installed, `uvicorn-0.5.1`, so I think it's a dependency problem when using a specific version of Python.

I am using Python 3.9.2 in Ubuntu 18.04 and everything is good. I'll try to reproduce the problem on the same docker container you are using for the tests `python:3.9-slim`.

**Comment by RobertoPrevato** [comment]
OK, I can reproduce the problem on `python:3.9-slim`. 

For some reason pip decides to implicitly downgrade the version of uvicorn along the way. Surprisingly, pip installs the last version of uvicorn just fine if I repeat a command `pip install -U uvicorn` after installing the dependencies from `requirements.txt`.

The good news is that `blacksheep` is behaving well and this is an issue with `requirements.txt` and what `pip` is doing. I'm looking for a solution.

**Comment by RobertoPrevato** [comment]
Found the issue:

it's a dependency mismatch between `blacksheep` and `uvicorn`: 

* the last version of blacksheep already updated to the last version of uvicorn
* the last version of uvicorn did not

```
    blacksheep 1.2.0 depends on httptools~=0.3.0
    uvicorn[standard] 0.15.0 depends on httptools==0.2.*; extra == "standard"
```

Funnily, the problem happens only when installing `uvicorn[standard]`. If we install them this way, everything works fine:

```
blacksheep>=1.2.0
gunicorn==20.1.0
uvicorn>=0.15.0
```

**Comment by waghanza** [comment]
> For some reason pip decides to implicitly downgrade the version of uvicorn along the way.

Yeah, I can see that and I do not understand what is going on

Seems to be the case with _Cython-based_ `uvicorn` dependencies (`uvicorn[standard]`)

**Comment by RobertoPrevato** [comment]
Please read my last comment. :) I wrote a stream of comments - sorry for spamming.
