### ISSUE TITLE
New PR for TechEmpower benchmarks

### ISSUE THREAD

**Issue by RobertoPrevato** [Neoteroi/BlackSheep#243]
**🚀 Feature Request**

Submit a new PR to TechEmpower Benchmarks.

* [Example](https://github.com/TechEmpower/FrameworkBenchmarks/tree/120dead50771de2208c3dd74b56f6c22829c3023/frameworks/Python/blacksheep)
* [Context](https://github.com/TechEmpower/FrameworkBenchmarks/pull/7210)

**Comment by remittor** [comment]
And why was your framework removed from the TFB repository?

I really liked the [performance](https://github.com/jamesroberts/fastwsgi/discussions/41#discussioncomment-5677004) of your framework!
I can try adding it to TFB repository again. I just want to understand what happened before.

**Comment by RobertoPrevato** [comment]
Hi @remittor 
It was removed only because the benchmark code in TechEmpower was outdated and I lacked the time to prepare a new example. The code in TechEmpower for blacksheep was still for one of the very first versions of blacksheep, that included a built-in implementation of HTTP Server (handling connections, TCP/IP connections with uvloop).

I later removed the HTTP Server and made blacksheep ASGI compatible ([I wrote about that here](https://robertoprevato.github.io/Presenting-BlackSheep/)). I couldn´t mantain both the web framework and the HTTP Server, I don´t have the time to do it. It might look weird, but I maintain all these projects in my private time, for passion, and I also have a full time job.

If you wish try adding a new PR for TechEmpower, I recommend maybe to wait for version 2 to become production stable? I added many improvements, and I'm working on more.

**Comment by RobertoPrevato** [comment]
> You shouldn't wait for this. With the advent of version 2.0, it will be possible to compare the speed.

You are right, it's a good idea. In the last months anyway I focused more on improving development UX and adding new features. Example: I think blacksheep has the best [OpenID Connect integration](https://github.com/Neoteroi/BlackSheep-Examples/tree/main/oidc) among Python web frameworks. Unfortunately I am not good at social network and PR, otherwise I think it would get more visibility.

**Comment by remittor** [comment]
Fresh TFB results:
![image](https://github.com/Neoteroi/BlackSheep/assets/9350115/eda462f6-0d1b-4f1b-8c52-32fc93fe2695)

Link: https://www.techempower.com/benchmarks/#section=test&runid=bc7f7570-a88e-48e3-9874-06d7dc0a0f74&l=hra0hr-35r&a=2

**Comment by RobertoPrevato** [comment]
Thank You, @remittor 
- You made my day, I'm super happy to see that BlackSheep is still going well on performance benchmarks. I know that my code is far from being perfect (there are some things I don't like and I plan to refactor), but I always strive to write efficient code and this shows off in these benchmarks.
- I appreciate you taking the time to make the PR for TechEmpower, and thank you for this
