### ISSUE TITLE
Add feature to handle validation errors (for example `pydantic.ValidationError`)

### ISSUE THREAD

**Issue by MaximZayats** [Neoteroi/BlackSheep#249]
##### _Note: consider using [Discussions](https://github.com/Neoteroi/BlackSheep/discussions) to open a conversation about new features…_

**🚀 Feature Request**
Hi!
Now if we use `pydantic` model, then there is no way to handle `pydantic.ValidationError`
We are getting `400 Bad Request` with `pydantic` error message:
```
Bad Request: 1 validation error for SomethingInput
foo
  value could not be parsed to a boolean (type=type_error.bool)
```
And if I want to send response with a `ValidationError.json()` this cannot be done. At least I don't find how :)

Are you have any plans for implement logic for handling errors like this ?

Code:
```python
class SomethingInput(BaseModel):
    name: str
    foo: bool


@app.router.post("/")
async def handler(i: FromJSON[SomethingInput]):
    return {"input": i.value}
```

**Comment by RobertoPrevato** [comment]
Hi @MaximZayats 
Thank You for opening this issue! While replying to your question, I see that this feature that can be improved and documented better.

It is possible to handle the exceptions that are thrown for bad requests by the framework itself, for example with:

```python
from blacksheep import Application, FromJSON, Request, text
from blacksheep.exceptions import HTTPException
from pydantic import BaseModel


class SomethingInput(BaseModel):
    name: str
    foo: bool


app = Application()


@app.exception_handler(400)
async def handle_bad_request(app, request: Request, http_exception: HTTPException):
    return text("Oh, No!", 400)


@app.router.post("/")
async def handler(i: FromJSON[SomethingInput]):
    return {"input": i.value}
```

```bash
$ curl -X POST http://127.0.0.1:8080/ -H 'Content-Type: application/json' -d '{"id": "foo"}'
Oh, No!
```

However, the inner exception from `pydantic` is lost and converted to the `str` message of the raise `HTTPException`. This is not good - the next version of the framework will be corrected. The only good news at the moment is that you can easily monkey-patch a method that I didn't code very well at the beginning, to behave better.

Like in this example:

```python
from blacksheep import Application, FromJSON, Request, text
from blacksheep.exceptions import HTTPException
from blacksheep.server.bindings import BodyBinder, InvalidRequestBody
from pydantic import BaseModel


class SomethingInput(BaseModel):
    name: str
    foo: bool


app = Application()


# monkey-patches the `parse_value` method to properly keep the inner exception using
# the raise ... from clause, to maintain the context of the inner exception in __context__
def parse_value(self, data: dict):
    try:
        return self.converter(data)
    except ValueError as value_error:
        raise InvalidRequestBody(str(value_error)) from value_error


BodyBinder.parse_value = parse_value


@app.exception_handler(400)
async def handle_bad_request(app, request: Request, http_exception: HTTPException):
    print(http_exception)
    return text("Oh, No!", 400)


@app.router.post("/")
async def handler(i: FromJSON[SomethingInput]):
    return {"input": i.value}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="127.0.0.1", port=8080, log_level="debug")
```

See this screenshot where I am debugging with VS Code:

![image](https://user-images.githubusercontent.com/2576032/163873371-66d7204b-92fc-4747-8caa-bee6fd78237c.png)

Note how monkey-patching the `parse_value` function of the BodyBinder class to use `raise ... from` allows to retrieve the original exception of the bad request from the `http_exception.__context__` property. I will probably look into a way to be more granular controlling this kind of error anyway - but the first fix is to use `raise ... from` in that method (I'll do a new release soon).

**Comment by RobertoPrevato** [comment]
The second snippet includes an example on how to use currently the `ValidationError.json()` while handling requests causing a bad request response.

**Comment by MaximZayats** [comment]
Sounds great. Thank you for quick response!
