### ISSUE TITLE
ValueError: Headers does not contain one header with the given key

### ISSUE THREAD

**Issue by 56907dzq** [Neoteroi/BlackSheep#271]
**ClientSession**

when make a request,the server doesn`t return a content-type header,  this line in connection.py will cause exception as the title recursive

https://github.com/Neoteroi/BlackSheep/blob/9fe7d66baf13456e3725f66f41cbc961285a8e2d/blacksheep/client/connection.py#L274

**Comment by RobertoPrevato** [comment]
Thank You for this bug report, I will fix the bug soon.
