### ISSUE TITLE
Invalid OpenAPI doc for route parameter with pattern

### ISSUE THREAD

**Issue by antipooh** [Neoteroi/BlackSheep#286]
Using route parameter with pattern, like `@get("{uuid:image_id}")` will generate the wrong parameter name `image_id` in openapi.json method description and Swagger make bad parameter substitutions on method request.  If manualy replace `image_id` to `uuid:image_id` all work well.

**Comment by RobertoPrevato** [comment]
Hi @antipooh 
Thank you for your interest and taking the time to open an issue. However, judging by the description you wrote, that is the intended behavior.

Everything that appears before the ":" in route parameters definition is intended to be used as additional information on the expected format of the route to match. The parameter name must be indeed what appears after the ":".

Example, let's say that you define this route:

```python
@get("/api/cats/{cat_id}")
``` 

In this case, the route matches any kind of ID, regardless of its format:

- `/api/cats/100` ✅
- `/api/cats/some-id` ✅
- `/api/cats/39a8ac6a-1adf-412a-a172-83ce8d2d7c3b` ✅

However, if you specify a route like this:

```python
@get("/api/cats/{uuid:cat_id}")
```

You are instructing the framework to only match requests when the path contains a parameter matching the pattern of a UUID (also called GUID).

Therefore, it will only match requests like this one:

- `/api/cats/39a8ac6a-1adf-412a-a172-83ce8d2d7c3b` ✅

**Comment by RobertoPrevato** [comment]
Fixed at 03534382258b9bc3121fde21a288b0c736472002
