### ISSUE TITLE
How to extend Black Sheep to multiple threads

### ISSUE THREAD

**Issue by WilliamSoCreat** [Neoteroi/BlackSheep#289]
##### _Note: consider using [Discussions](https://github.com/Neoteroi/BlackSheep/discussions) to open a conversation about new features…_

you know 
tornado  can do it 
though it will lead thundering herd(惊群效应,i dont know if it translate correct .or The herd effect
**🚀 Feature Request**

**Comment by RobertoPrevato** [comment]
Hi @WilliamSoCreat 
If you are thinking about using multiple threads to handle request handlers, then it's out of the scope of `blacksheep` now. You should look into how to do it with the underlying `ASGI` HTTP Server (e.g. `uvicorn`, `hypercorn`, etc.).

In the past `blacksheep` was not ASGI compatible and it implemented its own HTTP server - see [the before-asgi tag](https://github.com/Neoteroi/BlackSheep/releases/tag/before-asgi) - [files](https://github.com/Neoteroi/BlackSheep/tree/ef6a7f7d76ec8200ce66a260a118c3f80df8a1fd).

If instead you have in mind using multiple threads to handle CPU intensive operations, this can be done using the features offered by `asyncio` itself, that are [thread pool executors and process executors](https://docs.python.org/3/library/asyncio-eventloop.html#executing-code-in-thread-or-process-pools).

Example: let's imagine you want to resize pictures using `Pillow` as part of your request handling. In this scenario, you should use multi-threading using a ThreadPool executor to not block the event loop used to handle web requests. You can see an example of this here: [Torino /server/domain/pictures.py](https://github.com/Neoteroi/Torino/blob/9bac21735ed4e6bdaed6e8b20e2c6b33d76f938c/server/domain/pictures.py#L2).

I mentioned this in the `blacksheep` documentation but didn´t put an example there.

I hope this helps. 😄

**Comment by WilliamSoCreat** [comment]
uvicorn, hypercorn is what i want 
[thread pool executors and process executors](https://docs.python.org/3/library/asyncio-eventloop.html#executing-code-in-thread-or-process-pools) is what i want in the future 
thank you so much 😄
