### ISSUE TITLE
responses.file only returning attachment

### ISSUE THREAD

**Issue by Airiuwu** [Neoteroi/BlackSheep#303]
**Describe the bug**
A description of what the bug is, possibly including how to reproduce it.

**Comment by Airiuwu** [comment]
i accidentally submitted it too early

**Comment by Airiuwu** [comment]
While serving an image file over web, theres no option to have it be inline despite it being in the code
`content_disposition: ContentDispositionType = ContentDispositionType.ATTACHMENT`

**Comment by Airiuwu** [comment]
#304 I've created a pull request to make this a feature
syntax of the file object would be
`return file("filepath", "contenttype", <"attachment","inline">)`

**Comment by RobertoPrevato** [comment]
Hi @Airiuwu
I cannot reproduce the error you described. I tried to reproduce the error and, as I recalled, this feature is tested and working.

Example:

```python
from blacksheep import Application, ContentDispositionType, file, html

app = Application()


@app.router.get("/")
async def get_home():
    return html(
        """
        <h1>Test</h1>
        <p>An image inline:</p>
        <img src="/image" width="300" />
        """
    )


@app.router.get("/image")
async def get_image_inline():
    return file(
        "./pexels-satyabratasm-4001296.jpg",
        "image/jpeg",
        content_disposition=ContentDispositionType.INLINE,
    )

```

![image](https://user-images.githubusercontent.com/2576032/219705857-b2e09a97-2cfe-4e18-9613-f46d03150b67.png)

Looking at your PR, the only thing I can see is that you replaced the `Enum` with a string parameter. The current code covers already the possible scenarios:

```
Content-Disposition: inline
Content-Disposition: attachment
Content-Disposition: attachment; filename="filename.jpg"
```

**Comment by RobertoPrevato** [comment]
> #304 I've created a pull request to make this a feature syntax of the file object would be `return file("filepath", "contenttype", <"attachment","inline">)`

This is already possible with the current code API.

```python
    return file(
        "./pexels-satyabratasm-4001296.jpg",
        "image/jpeg",
        content_disposition=ContentDispositionType.INLINE,
    )

# --------

    return file(
        "./pexels-satyabratasm-4001296.jpg",
        "image/jpeg",
        file_name="some-attachment-name.jpg",
        content_disposition=ContentDispositionType.ATTACHMENT,  # default
    )

```
