### ISSUE TITLE
ClientSession  ssl error

### ISSUE THREAD

**Issue by 56907dzq** [Neoteroi/BlackSheep#305]
In my app, I used ClientSession of Blacksheep, like this:
        `async with ClientSession(connection_timeout=20.0, request_timeout=60.0, ssl=False) as client:`
        `    response = await client.get(url)`
I know remote website cert is expired, so I used `ssl=False`
But response is 
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] ,
not behave like requests's params verify.
Does it really work?

**Comment by RobertoPrevato** [comment]
Hi @56907dzq 
Sorry for the late response. This seems to be a bug, indeed. I look into this ASAP.

**Comment by RobertoPrevato** [comment]
@56907dzq 
Please upgrade to `1.2.10`, this bug is now fixed.
