### ISSUE TITLE
Dependency conflict between blacksheep and langchain

### ISSUE THREAD

**Issue by bitnom** [Neoteroi/BlackSheep#316]
I'm experiencing a dependency conflict between blacksheep and langchain, where the installation of blacksheep fails due to a version conflict with PyYAML.

After looking into the issue, I found that the main branch of blacksheep is already using an updated version of essentials-openapi, which uses PyYAML 6.0. However, the latest version of blacksheep on PyPI (v1.2.10) still depends on essentials-openapi version >=0.1.4,<1.0, which requires PyYAML version 5.4.1.

This conflict makes it impossible to install blacksheep alongside langchain, which requires PyYAML version >=6,<7.

I recommend updating blacksheep on PyPI so that it depends on a version of essentials-openapi that depends on PyYAML >= 6.0, so that users can install blacksheep alongside langchain without running into conflicts. The [requirements.txt](https://github.com/Neoteroi/BlackSheep/blob/main/requirements.txt) in the main-branch already satisfies this but [setup.py](https://github.com/Neoteroi/BlackSheep/blob/main/setup.py) oddly does not.

**Comment by RobertoPrevato** [comment]
Hi @bitnom 
Today I published your contribution to PyPi, both for:
- version 1 [https://pypi.org/project/blacksheep/1.2.11/](https://pypi.org/project/blacksheep/1.2.11/).
- version 2 (alpha) [https://pypi.org/project/blacksheep/2.0a3/](https://pypi.org/project/blacksheep/2.0a3/)
