### ISSUE TITLE
Constructor of JWTBearerAuthentication dosn't have algorithms parameter

### ISSUE THREAD

**Issue by tyzhnenko** [Neoteroi/BlackSheep#353]
The constructor of _JWTBearerAuthentication_ doesn't accept _algorithms_ parameter and doesn't pass it to _JWTValidator_. At the same time docstring of the constructor of _JWTBearerAuthentication_  contains a description of _algorithms_ parameter.

https://github.com/Neoteroi/BlackSheep/blob/c27b0f18337450ef69b04d474c091d324b61c184/blacksheep/server/authentication/jwt.py#L25-L36
https://github.com/Neoteroi/BlackSheep/blob/c27b0f18337450ef69b04d474c091d324b61c184/blacksheep/server/authentication/jwt.py#L54-L55
https://github.com/Neoteroi/BlackSheep/blob/c27b0f18337450ef69b04d474c091d324b61c184/blacksheep/server/authentication/jwt.py#L84-L92

**Comment by RobertoPrevato** [comment]
Thank You @tyzhnenko 
Sorry for late response here (busier days than usual). I merged your PR.
