### ISSUE TITLE
Using google oidc raise error on blacksheep endpoint

### ISSUE THREAD

**Issue by pavivin** [Neoteroi/BlackSheep#358]
Hi, I'm trying to use google oidc

```python
google_oidc = use_openid_connect(
    app,
    OpenIDSettings(
        authority="https://accounts.google.com/o/oauth2/v2/auth",
        client_id=settings.GOOGLE_CLIENT_ID,
        client_secret=settings.GOOGLE_CLIENT_SECRET,
        entry_path="/sign-in-google",
        logout_path="/sign-out-google",
        callback_path="/signin-google",
        discovery_endpoint="https://accounts.google.com/.well-known/openid-configuration",
    ),
    tokens_store=CookiesTokensStore(),
)
```

I trying to create my own profile endpoint 

```python
class AuthorizationController(Controller):
    @auth("user")
    @docs()
    @get("/api/profile")
    async def get_profile(self, user: Identity) -> Response[UserProfileView]:
        async with Transaction():
            user = await User.get_by_email(user.claims["email"])
            return Response(payload=UserProfileView(**user.as_dict()))

class AuthHandler(AuthenticationHandler):
    def __init__(self):
        pass

    async def authenticate(self, context: Request) -> Identity | None:
        header_value = context.get_first_header(b"Authorization")
        if header_value:
            token = header_value.decode().split()[-1]
            decoded_data = jwt.decode(
                token, settings.JWT_SECRET, algorithms=[settings.JWT_ALG], options={"verify_signature": True}
            )
            context.identity = Identity(claims=decoded_data, authentication_mode="access_token")
        else:
            context.identity = None
        return context.identity


app.use_authentication().add(AuthHandler())
app.use_authorization().add(Policy("user", AuthenticatedRequirement()))

```

I changed to something else but it didn't changed. I guess if it ends on profile no matter what it is

![image](https://github.com/Neoteroi/BlackSheep/assets/52045843/2eaac6f6-20a0-456e-8e3e-25f603fec924)

If I open it as HTML:
![image](https://github.com/Neoteroi/BlackSheep/assets/52045843/9e26f838-89c7-4283-8125-a6d6dee4d535)

It happens when I get endpoint without any header

**Comment by RobertoPrevato** [comment]
Hi @pavivin 
Thank you for reporting this issue, and sorry for replying so late. I did not check this, yet, because of lack of time. I will onfigure an OAuth app in Google and take a look.

**Comment by RobertoPrevato** [comment]
The first good news, is that I successfully tested a basic example where only an `id_token` is obtained from Google.

![image](https://github.com/Neoteroi/BlackSheep/assets/2576032/533b9879-83d3-47b4-a572-220cc7110752)

My example is like this (I will add it to the `BlackSheep-Examples` repository):

```python
"""
This example shows how to configure an OpenID Connect integration with Google, obtaining
only an id_token, exchanged with the client using a response cookie.
"""
import uvicorn
from blacksheep.server.application import Application
from blacksheep.server.authentication.oidc import OpenIDSettings, use_openid_connect

from common.routes import register_routes

app = Application(show_error_details=True)

client_id = "349036756498-715barque0aq00qplb3fon9i6hig7ib9.apps.googleusercontent.com"

# basic Google integration that handles only an id_token
use_openid_connect(
    app,
    OpenIDSettings(
        authority="https://accounts.google.com",
        client_id=client_id,
        callback_path="/authorization-callback",
    ),
)

register_routes(app)


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=5000, log_level="debug")
```

Now I try to configure an API access key, to verify if anything is wrong when handling `access_token`.

**Comment by RobertoPrevato** [comment]
I published my example to obtain `id_token` from Google here: https://github.com/Neoteroi/BlackSheep-Examples/tree/main/oidc

I see you are trying to use JWT Bearer authentication, the example I published is using cookie based authentication. But this  does not matter if you get a `redirect_uri_mismatch`, it means there is a misconfiguration: the URL you are using for your app does not match what is configured in your Google app.

My app is configured this way: 

![image](https://github.com/Neoteroi/BlackSheep/assets/2576032/4101cee9-b5b2-4eab-a60b-0f58081c5211)

It is also important to use `localhost`. If you enable a redirect URL such as `http://localhost:5000/example`, you cannot use `http://127.0.0.1:5000/example`, you need to use `localhost` when developing.

I also tested it with `BlackSheep` v1 and it works. Finally, if you wish to use JWT Bearer authentication, `blacksheep` version 2 offers built-in support for handling JWT Bearer tokens ([example here](https://github.com/Neoteroi/BlackSheep-Examples/blob/main/oidc/basic_storage_aad.py)). Version 1 supports only cookie based authentication. I almost finished making changes to `v2` and I will soon mark it as stable, but I still need to publish the updated documentation for it.

**Comment by pavivin** [comment]
Thank you.
Also i solved problem with parametr in oidc` is_default = False`
