### ISSUE TITLE
Google oidc on my https server

### ISSUE THREAD

**Issue by Nicialy** [Neoteroi/BlackSheep#378]
I dont understand why, but google oidc work differently on https server, he changed request with POST on GET.
Normal oidc my localhost:

https server:
![image](https://github.com/Neoteroi/BlackSheep/assets/43730314/1dd40794-f293-459e-9a14-7be3b057b2ad)
on my localhost
![image](https://github.com/Neoteroi/BlackSheep/assets/43730314/3ddb46a1-7535-4e4e-8568-858eef8ed921)
Why on my server google-callback changes type request?

**Comment by RobertoPrevato** [comment]
@Nicialy there is nothing in the BlackSheep OIDC implementation that can cause a different behavior depending on the scheme of the request. I used the OIDC integration with apps over HTTPS and didn´t experience such issue.
I tried with Google integration over HTTPS using ngrok, and it works as expected.

![image](https://github.com/Neoteroi/BlackSheep/assets/2576032/f80e50f8-1875-4d5e-bbb7-a6ef72f88a75)

If you don´t provide reproduction steps I cannot help more.

**Comment by RobertoPrevato** [comment]
I suspect, if you forget to add the right "Authorized redirect URL" with HTTPS scheme, and you have only one with HTTP, the identity provider can redirect you to the enabled value, with error information (redirect_uri_mismatch). In that case you can experience a redirect to a different scheme (as a collateral effect) when trying to make a user flow.
