### ISSUE TITLE
Request is undefined in jinja template

### ISSUE THREAD

**Issue by Kokoserver** [Neoteroi/BlackSheep#384]
i have this function to implement flash message
def flash(request: Request, message: typing.Any, category: str = "primary") -> None:
   if "_messages" not in request.session:
       request.session["_messages"] = []
       request.session["_messages"].append({"message": message, "category": category})

def get_flashed_messages(request: Request):
   print(request.session)
   return request.session.pop("_messages") if "_messages" in request.session else []

in which the flass function can be used to set the message, through session
and then i can set it like the following

@post()
async def test(self, request: Request):
   flash(request, "Failed to login", "danger")
   return self.view()

and i try to use in the template like this
{% for message in get_flashed_messages(request) %}
<div class="{{ message.category }}">{{ message.message }}</div>
{% endfor %} 

i should add that i use the mvc template and i already play with another method that doesn't use argument is works well.

i'm i the one access the request object wrong or there is a way to access session or request object differently.

**Comment by RobertoPrevato** [comment]
Also, please note the right way to implement your `flash` method is as follows:

```python
def flash(request, message, category: str = "primary") -> None:
    messages = request.session.get("_messages", [])
    messages.append({"message": message, "category": category})
    request.session["_messages"] = messages
```

Because if you modify the `_messages` property appending new messages, the `Session` object itself is not marked as modified, and the session does not get updated.

**Comment by Kokoserver** [comment]
Thanks for quick response. 🙏
