### ISSUE TITLE
TestClient Example from Documentation and from GIT/BlackSheep-Examples fails

### ISSUE THREAD

**Issue by xxxxxxbox** [Neoteroi/BlackSheep#400]
I’ve reproduced all steps by Coping/Pasting from official documentations https://www.neoteroi.dev/blacksheep/testing/ and **can't run test example**. Get different errors. I believe the official documentation is outdated and can’t be used for studding.

So, I downloaded **complete example from https://github.com/Neoteroi/BlackSheep-Examples/tree/main/testing-api**
and tried to run it. It **fails too**. Please find enclosed screenshot. I’ve tried to change versions of BlackSheep (1.2.18 / 2.0a9) and pydantic (1.10.10 / 2.0.2) in requrements.txt with no help. Tests always fail but due to selected version of packages can get additional errors.

**Please check if example at https://github.com/Neoteroi/BlackSheep-Examples/tree/main/testing-api can be fixed to use with some version of BlackSheep.**

And it would be great if you can update official documentation. Not only the article about testing but many other pages as they can’t be followed without getting errors.

Thanx.
![bs1](https://github.com/Neoteroi/BlackSheep/assets/56993366/2474c460-6c7d-48fe-abae-d6503fc08c57)

pip list                       
Package            Version
------------------ --------
annotated-types    0.5.0   
blacksheep         2.0a9   
certifi            2023.5.7
charset-normalizer 3.1.0
click              8.1.5
colorama           0.4.6
essentials         1.1.5
essentials-openapi 1.0.7
guardpost          1.0.2
h11                0.14.0
httptools          0.6.0
idna               3.4
iniconfig          2.0.0
itsdangerous       2.1.2
Jinja2             3.1.2
MarkupSafe         2.1.3
packaging          23.1
pip                22.3.1
pluggy             1.2.0
pydantic           2.0.2
pydantic_core      2.1.2
pytest             7.4.0
pytest-asyncio     0.21.1
python-dateutil    2.8.2
PyYAML             6.0
requests           2.31.0
rodi               2.0.2
setuptools         65.5.1
six                1.16.0
typing_extensions  4.7.1
urllib3            2.0.3
uvicorn            0.23.0
wheel              0.38.4

**Comment by RobertoPrevato** [comment]
Hi,
This was a mistake in the documentation. It was resolved with:
https://github.com/Neoteroi/BlackSheep-Docs/pull/29
