### ISSUE TITLE
Please release v2-dev onto PyPI

### ISSUE THREAD

**Issue by aabmets** [Neoteroi/BlackSheep#403]
I know that v2 is currently in the alpha stage, but I would like to already start building a new app on the v2 of Blacksheep. By the time we need to go to production with our app, the library will have already reached the stable stage. I could just copy-paste the main branch source code into my site-packages, but that is just inconvenient. When pydantic was in the pre-release stage with their v2, they made their unstable library available on PyPI, which enabled people to experiment with the changes and simplify giving feedback on any errors that they found. I would propose that doing the same for Blacksheep would be a good idea.

**Comment by RobertoPrevato** [comment]
Hi @aabmets 
BlackSheep version 2 is released to PyPi

![image](https://github.com/Neoteroi/BlackSheep/assets/2576032/34a5492f-42bb-473b-ae46-2da869a0abdc)

you can install the latest alpha with `pip install blacksheep==2.0a9`.

By the way, these days I am working on updating the documentation. I will make `v2` stable as soon as I publish its documentation, and I don´t plan any more breaking changes.

**Comment by aabmets** [comment]
Thanks!
