### ISSUE TITLE
add Python 3.12 support

### ISSUE THREAD

**Issue by bymoye** [Neoteroi/BlackSheep#425]
In python3.12, datetime.utcnow() has been issued a deprecation warning:

datetime.utcnow() is deprecated and scheduled for "
                       "removal in a future version. Instead, Use timezone-aware "
                       "objects to represent datetimes in UTC: "
                       "datetime.datetime.now(datetime.UTC).

and

Then in setuptools, there is such a warning:
`Use of pkg_resources is deprecated in favor of importlib.resources, importlib.metadata and their backports (importlib_resources, importlib_metadata). Some useful APIs are also provided by packaging (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.`
I think we should adapt to them

**Comment by bymoye** [comment]
In the mimetypes module of python3.12, application/javascript becomes text/javascript

**Comment by RobertoPrevato** [comment]
Completed with https://github.com/Neoteroi/BlackSheep/commit/310dc281641dc89f23b8d0dbbaca0caee2449304
🎉
