### ISSUE TITLE
Mount problem   

### ISSUE THREAD

**Issue by 15864620573** [Neoteroi/BlackSheep#443]
```
from blacksheep import Application

parent = Application()


@parent.router.get("/")
def parent_home():
     return "Hello, from the parent app"
 
 
child = Application()
 
 
@child.router.get("/")
def child_home():
     return "Hello, from the child app"


parent.mount_registry.auto_events = True

parent.mount("/sub", child)

```

For example, in this example, although it is mounted, it will not start and will give a route conflict error.

Why is that? Isn't it already mounted?

**Comment by RobertoPrevato** [comment]
I forgot to mention, @15864620573, if you want to disable the default singleton router, you can use the Environment Variable `APP_DEFAULT_ROUTER` and set it to 'false' or '0'.
