### ISSUE TITLE
Upgrade SwaggerUI to version 5

### ISSUE THREAD

**Issue by sinisaos** [Neoteroi/BlackSheep#447]
It's not really a bug, but after upgrading Piccolo ORM to V1 (migrate to Pydantic v2) in Piccolo Blacksheep asgi template request body is empty if we use [create_pydantic_model](https://github.com/piccolo-orm/piccolo/blob/master/piccolo/apps/asgi/commands/templates/app/_blacksheep_app.py.jinja#L39-L45) (Pydantic BaseModel works fine). [Here's the conversation](https://github.com/piccolo-orm/piccolo/pull/911#issuecomment-1854623188). If this makes sense to you, I can make a PR with those small changes, if not, feel free to close this issue. Thank you.

**Comment by RobertoPrevato** [comment]
Hi @sinisaos 
Sure, a PR is welcome!

**Comment by sinisaos** [comment]
@RobertoPrevato Thanks for quick response. I will make PR during the day.
