### ISSUE TITLE
Add a `is_disconnected` property to Request, similar to Starlette

### ISSUE THREAD

**Issue by netanel-haber** [Neoteroi/BlackSheep#452]
**🚀 Feature Request**
Starlette exposes an `is_disconnected` api on `Request`:
https://github.com/encode/starlette/blob/23c81da94b57701eabd43f582093442e6811f81d/starlette/requests.py#L291
<img width="689" alt="image" src="https://github.com/Neoteroi/BlackSheep/assets/58652339/fe8a54c7-def5-4124-bd33-e24da04a1a23">

In streaming situations, it would be useful to be able to have that information available, in order to be able to cancel work within request handlers.

**Comment by RobertoPrevato** [comment]
Hi @netanel-haber 
Thank You for bringing this up, I will gladly look into this, these days I am working on a private application where long polling might be useful.

**Comment by netanel-haber** [comment]
> Thank You for bringing this up, I will gladly look into this, these days I am working on a private application where long polling might be useful.

Hey, thanks for the reply. I ended up implementing this in a pretty wonky way:

1. I created a `CustomApplication` that inherits from `Application`, and overrides `_handle_http` just so I could grab `receive` [I'm using `Uvicorn`].

2. Then, Inject:
```python
scope["state"]["receive"] = receive
```

3. Finally, I can access `receive` in Route handlers, off of the scope state, and listen on `http.disconnect`. I ended up writing an `on_disconnect` function that receives a callback and ```python
while True: 
  await receive()
``` 
until receiving the disconnect event, then executes the callback. This is executed in a `create_task` call.


*Feature requests/suggestions:*

1. Step 1 could be cleaner if BlackSheep would support ASGI middleware, (which I think I saw in another issue, and was labeled "Won't Fix"?).

2. Step 2 could be cleaner. Right now, the `ASGIScope` type exported by BS doesn't contain the `state` key - I read the relevant ASGI spec and that is correct, as the `state` key is optional and at the implementer discretion. But it would be useful if you would add `state` as `Optional` to the `TypedDict`, so mypy doesn't complain about it (as `Uvicorn` has it both typing wise and physically).

3. Finally, obviously exposing receive somehow, or providing a more high level `is_disconnected`/`on_disconnect` would be optimal. It would also be useful if there was an api to detect whether a request handler had run to completion or not (request.completed?), since `http.disconnect` is sent whether or not the request ended gracefully, and you might want fine-grained control on whether or not to execute the callback depending if it is a graceful completion or not. 

Essentially, `on_disconnect` that executes whether or not a request completed gracefully is more or less a the `BackgroundTasks` api exposed by Starlette (and FastAPI), so that's two birds with on stone.

**Comment by RobertoPrevato** [comment]
Hi @netanel-haber 
I added two features you requested at https://github.com/Neoteroi/BlackSheep/commit/8d9321c05d5ba150ab09bf6c09fd8d31d02f9b7d

1. A `is_disconnected()` method that, in many tests I made, works like in Starlette both with uvicorn and Hypercorn
2. I made the `receive` callable accessible to Python code, through the existing `ASGIContent` class. Receive was already documented in `messages.pyi` file, and therefore it should have be made not-Cython only.

```python
@app.router.get("/read-asgi-receive")
def check_asgi_receive_readable(request: Request):
    content = request.content
    assert isinstance(content, ASGIContent)

    receive = content.receive
    assert callable(receive)
```
I plan to release this feature to PyPi today.

---

I made tests with Starlette, uvicorn, and Hypercorn, and found out that Hypercorn does not work in the same way like uvicorn and requires calling `is_disconnected()` more than once (for some reason, it doesn't work the first time). I also noticed that Starlette requires returning anyway some kind of Response compatible with ASGI scope / send / receive API, even if the request is disconnected (might be a no-op response that does nothing).

**Comment by RobertoPrevato** [comment]
I updated the [long polling example](https://github.com/Neoteroi/BlackSheep-Examples/tree/main/long-polling) to include a `request.is_disconnected()` part and a timeout on the server side.

**Comment by netanel-haber** [comment]
Thank you!

**Comment by netanel-haber** [comment]
> Finally, obviously exposing receive somehow, or providing a more high level is_disconnected/on_disconnect would be optimal. It would also be useful if there was an api to detect whether a request handler had run to completion or not (request.completed?), since http.disconnect is sent whether or not the request ended gracefully, and you might want fine-grained control on whether or not to execute the callback depending if it is a graceful completion or not. Right now, the only way I can see for doing that is checking if request.scope is None, since: ["... the connection scope will persist until the response closes from either the client or server side."](https://asgi.readthedocs.io/en/latest/specs/www.html#http-connection-scope). But that seems dangerous and not guaranteed.

Another question though, regarding `3.` above - I'm currently using the following hacky code:
```python
async def await_premature_disconnect() -> None:
  while True:
    message = await receive()
    if request.scope is None:
      return
    if message.get("type") == "http.disconnect":
      """`http.disconnect` was raised prematurely *before* handler has returned"""
      on_disconnect()
      return
``` 

Is there a more robust way to do so?

**Comment by RobertoPrevato** [comment]
> Is there a more robust way to do so?

If the objective is to close inactive requests (like every 5 seconds), I think using a background task like you are doing is a good approach. I updated my long polling example to include this feature, I would do something like you can see here:

https://github.com/Neoteroi/BlackSheep-Examples/tree/main/long-polling

I would use a timeout so that requests are not kept open indefinitely in any case, and having a periodic task checking for inactive requests every _n_ seconds and cancelling their tasks.

```python
async def periodic_check():
    """
    Periodically checks if active long-polling requests are disconnected, and cancels
    them if needed.
    """
    while True:
        await asyncio.sleep(5)  # Example: check every 5 seconds

        print("Checking active connections...")

        for item in manager._active_requests:
            request = item.request
            if await request.is_disconnected():
                print(f"Request {id(request)} is disconnected, cancelling its task...")
                item.task.cancel()


@app.on_start
async def start_periodic_check():
    asyncio.create_task(periodic_check())
```

The timeout part:

```python
    async def wait_for_message(self, request, queue):
        try:
            async with asyncio.timeout(self._timeout):
                message = await queue.get()

                # Note: here it is possible to check if the request is
                # disconnected using: if await request.is_disconnected()
                #
                # This can be useful to avoid consuming operations from this point,
                # or to cancel tasks.
                if await request.is_disconnected():
                    print("🔥🔥🔥 Request is disconnected!")
                    return
                return text(message)
```

Personally I would approach it that way. PS. I would like to make a test with Redis Pub/Sub and see how that would work in a multi-instance application.

**Comment by RobertoPrevato** [comment]
Hi @netanel-haber 
Inspired by your request for this feature and the example for long-polling, I improved the framework with built-in features for server-sent events. Might be interesting for you https://www.neoteroi.dev/blacksheep/server-sent-events/

I also added support for request handlers defined as asynchronous generators, which in my opinion makes for a good UX when using SSE.

**Comment by netanel-haber** [comment]
@RobertoPrevato  Just used your SSE support, thanks!
