### ISSUE TITLE
Mounting applications

### ISSUE THREAD

**Issue by lbsx** [Neoteroi/BlackSheep#486]
```python
import uvicorn
from blacksheep import Application

parent = Application()


@parent.router.get("/")
def parent_home():
    return "Hello, from the parent app"


child = Application()


@child.router.get("/")
def child_home():
    return "Hello, from the child app"


# Note: when mounting another BlackSheep application,
# make sure to handle the start and stop events of the mounted app
parent.mount_registry.auto_events = True

parent.mount("/sub", child)


if __name__ == "__main__":
    uvicorn.run("multiapp:app", host="0.0.0.0", port=5556)

```
I got the code from [blacksheep](https://www.neoteroi.dev/blacksheep/mounting/)
When I run it, it throws an error，
Traceback (most recent call last):
  File "/home/leib/code/py/web/xy/multiapp.py", line 12, in <module>
    child = Application()
  File "/home/leib/.pyenv/versions/3.10.13/lib/python3.10/site-packages/blacksheep/server/application.py", line 213, in __init__
    validate_router(self)
  File "/home/leib/.pyenv/versions/3.10.13/lib/python3.10/site-packages/blacksheep/server/routing.py", line 963, in validate_router
    raise SharedRouterError()
blacksheep.server.routing.SharedRouterError: Invalid routers configuration: the same router is used in more than one Application object. When working with multiple applications, ensure that each application is configured to use different routers. For more information, refer to: https://www.neoteroi.dev/blacksheep/routing/

**Comment by lbsx** [comment]
@mingwiki  那个代码是https://www.neoteroi.dev/blacksheep/mounting/里的官方示例，把路由改成其他的，也一样报这个错，把路由全删了只留两个app也报这个错.

**Comment by sinisaos** [comment]
@lbsx The documentation has not been updated, but fix is to instantiate a specific router in one of your applications as described in this [issue](https://github.com/Neoteroi/BlackSheep/issues/443#issuecomment-1847469061).

**Comment by lbsx** [comment]
@sinisaos  Thank you for helping me solve my doubts
