### ISSUE TITLE
Optimal way to use SQLAlchemy with dataclasses

### ISSUE THREAD

**Issue by Mrdhaaw** [Neoteroi/BlackSheep#510]
How can i use `SQLAlchemy` with `Blacksheep` 
i am using `SQLAlchemy` `MappedAsDataclass` this is an example:
```python
class Clip(Base):
	__tablename__ = "clip"
	name: Mapped[str] = mapped_column(String(128))
	filename: Mapped[str] = mapped_column(String(128))
	clip_type: Mapped[ClipType]
	
	tags: Mapped[List["Tag"]] = relationship(secondary=ClipTag,back_populates="clips")
```

and every time i try to convert it to a dict or to json i get and Error:
`RecursionError: maximum recursion depth exceeded`

What is The best solution for this should i use `Pydantic` or should i add a to_dict method to every class

**Comment by tyzhnenko** [comment]
Hey @Mrdhaaw. 

Blacksheep supports Pydantic models and dataclasses to build OpenAPI schema. It has data binders that support Pydantic models as well. So, I decided to use Pydantic with BlackSheep in my project in general
