### ISSUE TITLE
How BlackSheep can be used for streaming video content? 

### ISSUE THREAD

**Issue by abhinavatai** [Neoteroi/BlackSheep#80]
Hey, 
I am just curious about any built-in method BlackSheep has for streaming video content using http 206 or other?

**Comment by RobertoPrevato** [comment]
Hi @abhinavatai 
Streamed content is supported, using asynchronous generators. There is built-in support for HTTP 206 Partial Content responses, in relation to Range requests for static files, that are automatically handled by the web framework. This means that the framework supports out of the box resumable download of files, and streaming videos at specific points, like resuming the reproduction of a video at a specific point of its timeline. For example, HTML5 Video element handles this automatically and so does my web framework. Again, this is handled when using `serve_static_files`.
You can see the source code of this feature [here](https://github.com/RobertoPrevato/BlackSheep/blob/master/blacksheep/server/files/__init__.py).

If you wish to write your own logic that streams a video with partial content (for example reading an input from a camera and serving it), please start from the most basic example of streamed content using async generators, documented here: [Chunked Encoding](https://www.neoteroi.dev/blacksheep/responses/#chunked-encoding).

**Comment by abhinavatai** [comment]
@RobertoPrevato Thanks for your quick response. 

I checked the source code you shared and it is quite similar to custom logic I have written to use with flask/quart.

Although flask/quart has a method `send_file` to send a file with an optional boolean argument `conditional` which when set to `True`, converts the response to HTTP 206 Partial Content for streaming the same way.

But I don't use this `send_file` method in flask/quart for streaming, since it does not allow me to control the chunk size. 
And it sometimes fails in case of large files. 

I was looking for something like that in BlackSheep. But I think `StreamedContent` will solve most of the purpose here.
