### ISSUE TITLE
Add support for websocket

### ISSUE THREAD

**Issue by Bloodielie** [Neoteroi/BlackSheep#88]
Websocket

**Comment by RobertoPrevato** [comment]
Hi @Bloodielie and @tiptop96, thanks for your interest. 😄 
Yes, I am planning to implement an abstraction layer for WebSockets, but right now I don't know yet when I will start. By the way, any contribution is welcome: in case, the implementation should be compatible with the abstraction layer provided by ASGI for web sockets.

The good news is that, even if I won't work immediately on WebSockets, in the last days I've been working on a personal project using my web framework, the improved version of [my data storage](https://robertoprevato.github.io/How-I-created-my-own-media-storage-in-Azure/), and in the process I found some things to improve / correct in the web framework.

Moreover, I will be able to share some of the parts I wrote for this project, to provide examples and better documentation, for example:
* how to create a database connections pool to PostgreSQL using `asyncpg` and having it injected by dependency injection, and close it gracefully when the application is stopped
* how to implement [JWT Bearer authentication](https://robertoprevato.github.io/Validating-JWT-Bearer-tokens-from-Azure-AD-in-Python/) using JWTs issued by Azure Active Directory for a server side API
* how to implement authorization by claims in the user's JWT
* how to implement OIDC (OpenID Connect) integration with Azure Active Directory and store user's information in sessions (I added support for sessions just [11 days ago](https://github.com/Neoteroi/BlackSheep/commit/6c72b1e72384076fefd0560c9bcffee24c26e8d4), [Sessions docs](https://www.neoteroi.dev/blacksheep/sessions/))
* how to deploy the application to Azure App Service using GitHub Workflows
* how to provision the necessary services for deployment in Azure using GitHub Workflows and ARM templates deployment

**Comment by tiptop96** [comment]
That sounds awesome! I'm looking forward to reading it all!

If I find the time I will deffo contribute, I actually had some time to play around with it after work today and I am loving it so far! I built a middleware to coerce choosen types into the `Response` type allowing you to do stuff like this!

```python
@get("/")
async def home() -> dict:
    return {"woo": "wii"}
```

```python
@get("/")
async def home() -> dict:
    return "Wohoo"
```
Will be exploring the framework further soon!

Btw unrelated to this issue I just realized that I read an [article](https://robertoprevato.github.io/Upgrading-Azure-Storage-Python-SDK-to-support-asyncio/) by you a few weeks ago on upgrading the Azure Storage SDK. Great write up, thanks for that!

**Comment by kun1996** [comment]
This is my socket implementation
It's just a simple implementation. There's still a long way to go before it's done
At present, I'm thinking about how to integrate into blacksheet

```python
import enum
import functools


class AuthError(Exception):
    pass


class WebSocketDisconnect(Exception):
    def __init__(self, code: int = 1000):
        self.code = code


class WebSocketState(enum.Enum):
    CONNECTING = 0
    CONNECTED = 1
    DISCONNECTED = 2


class WebSocket:

    def __init__(self, scope, receive, send):
        assert scope['type'] == 'websocket'

        self._scope = scope
        self._receive = self._wrap_receive(receive)
        self._send = send

        self.client_state = WebSocketState.CONNECTING
        self.application_state = WebSocketState.CONNECTING

    async def __aenter__(self):
        await self.connect()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if isinstance(exc_type, WebSocketDisconnect):
            # TODO: client clode connection
            pass
        else:
            await self.close()

    @property
    def _meta_data(self):
        return self._scope

    def auth(self):
        pass

    async def connect(self):
        message = await self._receive()
        assert message['type'] == 'websocket.connect'

        self.client_state = WebSocketState.CONNECTED
        try:
            # TODO: auth something
            self.auth()
        except AuthError:
            return await self.close(403)

        await self.accept()

    async def accept(self, subprotocol: str = None):
        self.application_state = WebSocketState.CONNECTED

        message = {
            'type': 'websocket.accept',
            'subprotocol': subprotocol
        }

        # TODO: headers key added in spec version 2.1, but HTTP/2 and HTTP/3 ) must not be present

        await self._send(message)

    async def receive(self) -> dict:
        assert self.application_state == WebSocketState.CONNECTED

        message = await self._receive()
        assert message['type'] == 'websocket.receive'

        return message

    async def receive_text(self):
        return await self.receive().get('text')

    async def receive_bytes(self):
        return await self.receive().get('bytes')

    async def send(self, message):
        assert self.client_state == WebSocketState.CONNECTED
        await self._send(message)

    async def send_text(self, data: str):
        await self.send({
            "type": "websocket.send",
            "text": data
        })

    async def send_bytes(self, data: bytes):
        await self.send({
            "type": "websocket.send",
            "bytes": data
        })

    def _wrap_receive(self, _receive):

        @functools.wraps(_receive)
        async def disconnect():
            message = await _receive()

            if message["type"] == "websocket.disconnect":
                self.application_state = self.client_state = WebSocketState.DISCONNECTED

                raise WebSocketDisconnect(message["code"])
            return message

        return disconnect

    async def close(self, code: int = 1000):
        self.application_state = self.client_state = WebSocketState.DISCONNECTED

        await self._send({
            "type": "websocket.close",
            "code": code
        })


# ================== test_code ====================
# import pyx if you pip install blacksheep, you can delete it
import pyximport

pyximport.install()

import uvicorn
from blacksheep.server import Application
from blacksheep.server.responses import html


class WSApplication(Application):

    async def __call__(self, scope, receive, send):
        if scope['type'] == 'websocket':
            await self.websocket(scope, receive, send)
        else:
            await super().__call__(scope, receive, send)

    async def websocket(self, scope, receive, send):

        async with WebSocket(scope, receive, send) as ws:
            for _ in range(3):
                _s = await ws.receive()
                print(_s)
                _s['type'] = 'websocket.send'
                await ws.send(_s)


s = """
<!DOCTYPE html>
<html>
    <head>
        <title>Chat</title>
    </head>
    <body>
        <h1>WebSocket Chat</h1>
        <form action="" onsubmit="sendMessage(event)">
            <input type="text" id="messageText" autocomplete="off"/>
            <button>Send</button>
        </form>
        <ul id='messages'>
        </ul>
        <script>
            var ws = new WebSocket("ws://localhost:8000/ws");
            ws.onmessage = function(event) {
                var messages = document.getElementById('messages')
                var message = document.createElement('li')
                var content = document.createTextNode(event.data)
                message.appendChild(content)
                messages.appendChild(message)
            };
            function sendMessage(event) {
                var input = document.getElementById("messageText")
                ws.send(input.value)
                input.value = ''
                event.preventDefault()
            }
        </script>
    </body>
</html>
"""

app = WSApplication()


@app.route("/")
async def home():
    return html(s)


if __name__ == '__main__':
    uvicorn.run('websocket:app')

```

**Comment by myusko** [comment]
@RobertoPrevato Probably we can start work on it.

**Comment by RobertoPrevato** [comment]
@myusko I agree. By the way, back in March I tested the example that @kun1996 kindly prepared (thank you again - I only reacted with a ❤️ back in March and that was meant as a thank you) - and it's a useful example. 

It seems that some more event must be handled because it works for a few messages, then it stops working. @myusko if you have time and will, please read how it is done in Starlette (just to know what are the ASGI messages that need to be handled). These days I still want to dedicate time to the documentation, since I suspended that for the other things. 😄

**Comment by myusko** [comment]
@RobertoPrevato Yeah, once I've got a free time, I will take a look, and will start work on that.
